 SQL QUERIES FOR CUSTOMER DATA ANALYSIS 

-- Q1 What is the total revnue generated by the male vs female customers?

select gender,SUM(purchase_amount) as revenue
from customer_data
group by gender;

-- Q2 Which customer used a discount but still spent more than the average purchased amount?

select customer_id, purchase_amount
from customer_data
where discount_applied= 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_data);

-- where ke baad vala select avg(customer_amount) >= iske baad likhta hai naa ki final table mein
--select customer_id, purchase_amount
--from customer_data
--where discount_applied= 'Yes' and purchase_amount >=  AVG(purchase_amount);
-- aise likhna is not right bcz where mein aggregate functions nhi likh skte

-- Q3 which are the top 5 products with the highest average review rating?

select item_purchased , AVG(review_rating) as "AVERAGE PRODUCT RATING"
from customer_data
group by item_purchased
order by AVG(review_rating) desc   -- IDHR INSTEAD OF order by AVG(review_rating) U CAN ALSO WRITE order by "AVERAGE PRODUCT RATING"
limit 5;

-- Q4 Compare the average purchase amount between standard and express shipping

select shipping_type , ROUND(AVG(purchase_amount),2)
from customer_data
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

--Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers

select subscription_status, COUNT(customer_id) as total_customers, 
ROUND(AVG(purchase_amount),2) as average_spend, ROUND(SUM(purchase_amount),2) as total_revenue
from customer_data
group by subscription_status
order by total_revenue , average_spend desc;  – isme phle total revenue se sort hoga agar vo same hai then average spend se hoga

-- Q6 Which 5 products have the highest percentageof purchases with discounts applied?

SELECT
    item_purchased,
    ROUND(
        SUM(CASE
                WHEN discount_applied='Yes' THEN 1
                ELSE 0
            END)
        *100.0/COUNT(*),
        2
    ) AS discount_percentage
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7 Segment customers into New , Returning and Loyal based on their total number of previous purchases and show count of each segment

SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_data
GROUP BY customer_segment;


-- Q8 Which are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10 What is the revenue contribution of each age group?

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;
